In [2]:
import pandas as pd

pd.read_csv("world_df.csv")

,Entity,Code,Year,Annual CO₂ emissions,Annual CO₂ emissions including land-use change,Annual CO₂ emissions from land-use change
0,World,OWID_WRL,1850,1.968960e+08,2.621609e+09,2.424713e+09
1,World,OWID_WRL,1851,1.988050e+08,2.711943e+09,2.513138e+09
2,World,OWID_WRL,1852,2.075509e+08,2.758550e+09,2.550999e+09
3,World,OWID_WRL,1853,2.172092e+08,2.825733e+09,2.608524e+09
4,World,OWID_WRL,1854,2.551390e+08,2.886013e+09,2.630874e+09
...,...,...,...,...,...,...
167,World,OWID_WRL,2017,3.609674e+10,4.042868e+10,4.331947e+09
168,World,OWID_WRL,2018,3.682651e+10,4.100787e+10,4.181357e+09
169,World,OWID_WRL,2019,3.708256e+10,4.163984e+10,4.557283e+09
170,World,OWID_WRL,2020,3.526409e+10,3.932185e+10,4.057758e+09
171,World,OWID_WRL,2021,3.712385e+10,4.106290e+10,3.939044e+09